I consistently prioritize and complete all assigned trainings and employee obligations on time. My commitment to meeting deadlines is reflected in my proactive approach to time management. Over the past year, I achieved a 100% completion rate on mandatory trainings and a 100% on-time submission of required tasks and tickets. I am open to feedback and continuously seek ways to enhance my efficiency in order to contribute to the team's success. Moreover, I actively engage in additional learning opportunities to stay abreast of industry trends, ensuring that my skill s and knowledge remains up-to-date, which further supports the company's goals. I have even started a few learning programs on Udemy and other online learning platforms.

L1 ativities - 
In code migration, my precision and diligence have resulted in a 100% success rate over the past year.
I have helped the developers with building the shell script to run a process and setting up the schedules for the process in production ensuring that the process is tested end-to end in production with all the libraries and credentials. Meticulous job monitoring and prompt actions in case of failures have been instrumental in maintaining a stable production environment and ensuring providing timely outputs to the BU's.
Incase of ad-hoc runs and timeline loans processing, I have always ensured to provide the Business Units, a timely status updates.
I have also shown my cooperation in working in different work shift according to the availability of other team members which has helped the team to not miss any failure of any jobs and ensuring that the support team is always available. I have consistently recommended developers for code fixes, leading to a remarkable 50% reduction in failures. This strategic approach not only showcases my technical expertise but also aligns seamlessly with the organization's goals of a resilient and efficient production environment.

development - 
In the past year, I led the successful development of Project Romeo - BKFS PLS Investor Rules, utilizing my skills in Python selenium and SQL database connections to build the entire solution from inception to execution and testing which got QC approved. This project not only demonstrated my technical proficiency but also showcased my ability to manage end-to-end development seamlessly. 
Moreover, when a team member left, I proactively took over the project - BKFS Final Mod, ensuring the a smooth transition and implementing necessary changes and enhancements based on Business Units requirements. My contributions extended beyond project initiation, as I continued to collaborate with the development team, providing valuable testing support and making enhancements to existing projects, including Foreclosure-Escrow Breakdown, Cisco-email automation. This multifaceted approach not only strengthened the team's capabilities but also resulted in successful project deliveries and satisfied BU's requirements and this also ensured timely closing of service desk tickets.


In the context of the Experimentation initiative, I actively contributed to building future automation capabilities, this involved innovatively using bots and servers in the support team, automating scripts for efficient server storage management, include the removal of old dump files. Additionally, I identified and repurposed vacant bots for the deployment of our main project  - Project Romeo, aligning with the goal of ensuring smooth operations and process execution.

I take immense pride in excelling at customer service, consistently providing exceptional support to Business Units (BU's). I actively engage with them through regular meetings, ensuring a deep understanding of their needs and process requirements. I empower them by providing necessary tools and reports such as API for various processes, fostering independence. My commitment to maintaining a high NPS is reflected in my proactive approach to update processes and reconfiguring systems based on valuable feedback. I prioritize timely responses to Business Units, ensuring clear and effective communication between teams. 
I have always tried to keep them updated regarding any process by live monitoring and providing them the status of execution. My dedication to superior customer service has consistently positioned our team at the forefront of client satisfaction within the organization.
 
